---
policy:
  approval:
    - or:
        - pre-approved signatures
        - dependabot-patch
        - dependabot-minor
        - and:
            - default-review
            - protected-files
  disapproval:
    requires:
      teams:
        - "Sea-Shell/seashell"

approval_rules:
  - name: pre-approved signatures
    description: Do not require approval if signed by team
    if:
      has_author_in:
        teams:
          - "Sea-Shell/seashell"
      has_valid_signatures: true
      has_valid_signatures_by:
        teams:
          - "Sea-Shell/seashell"
    options:
      request_review:
        enabled: false
    requires:
      count: 0

  - name: dependabot-patch
    description: Do not require approval for Dependabot patch update
    if:
      author_is_only_contributor: true
      has_author_in:
        users:
          - "sea-shell-renovate[bot]"
      has_labels:
        - "dependencies"
        - "patch"
      has_valid_signatures: true
    options:
      request_review:
        enabled: false
    requires:
      count: 0

  - name: dependabot-minor
    description: Do not require approval for Dependabot minor update
    if:
      author_is_only_contributor: true
      has_author_in:
        users:
          - "sea-shell-renovate[bot]"
      has_labels:
        - "dependencies"
        - "minor"
      has_valid_signatures: true
    options:
      request_review:
        enabled: false
    requires:
      count: 0

  - name: default-review
    description: Require approval by maintaining team
    options:
      request_review:
        enabled: true
        mode: teams
    requires:
      count: 1
      permissions:
        - "write"
      teams:
        - "Sea-Shell/seashell"

  - name: protected-files
    description: Require two approvals for protected files
    if:
      only_changed_files:
        paths:
          - ".policy.ya?ml$"
          - ".bulldozer.ya?ml$"
          - "renovate.ya?ml$"
          - "^.github/.*$"
    options:
      request_review:
        enabled: true
        mode: teams
    requires:
      count: 1
      teams:
        - "Sea-Shell/seashell"
