---
policy:
  approval:
    - and:
      - status checks
      - or:
        - seashell-approval
        - dependabot-patch
        - dependabot-minor
  disapproval:
    requires:
      teams:
        - "Sea-Shell/owners"

approval_rules:
  - name: status checks
    description: A rule that requires status checks to be green
    if:
      has_successful_status:
        - "Commit linting"
        - "Golang linting"
  
  - name: seashell-approval
    description: A rule that requires approval from one in a team
    if:
    requires:
      count: 1
      teams:
        - "Sea-Shell/owners"
    options:
      request_review:
        enabled: true
        mode: teams

  - name: dependabot-patch
    description: Rule to approve PR when label is patch, author is dependabot
    if:
      has_author_in:
        users:
          - "dependabot[bot]"
      author_is_only_contributor: true
      has_labels:
        - "dependencies"
        - "patch"
      has_valid_signatures: true
    requires:
      count: 0

  - name: dependabot-minor
    description: Rule to approve PR when label is minor, author is dependabot
    if:
      has_author_in:
        users:
          - "dependabot[bot]"
      author_is_only_contributor: true
      has_labels:
        - "dependencies"
        - "minor"
      has_valid_signatures: true
    requires:
      count: 0
