# service account
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: yt-dlp-sa
# secret
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: yt-dlp-secret
  annotations:
    kubernetes.io/service-account.name: "yt-dlp-sa"