apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
  name: yt-dlp
  namespace: seashell
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: yt-dlp
        spec:
          containers:
          - env:
            - name: TZ
              value: Europe/Oslo
            image: registry.hub.docker.com/bateau/ytdlp:1.2.0
            imagePullPolicy: Always
            name: yt-dlp
            volumeMounts:
            - mountPath: /home/abc/yt-dlp
              name: config
            - mountPath: /library
              name: library
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          securityContext:
            runAsGroup: 1000
            runAsUser: 1000
          terminationGracePeriodSeconds: 480
          volumes:
          - hostPath:
              path: /data/disk2/opt/youtube-dl
              type: ""
            name: config
          - hostPath:
              path: /data
              type: ""
            name: library
  schedule: 0 */6 * * *
  startingDeadlineSeconds: 360000
  successfulJobsHistoryLimit: 2
  suspend: false