---
on:
  pull_request:
    branches:
      - main

name: Commit lint
jobs:
  lint:
    uses: nrkno/github-workflow-semantic-release/.github/workflows/workflow.yaml@0ae0866d8c7d8e2304ddcbc6e5abfeb76affc28e # v4.14.0
    with:
      runs-on: ubuntu-latest
      release-enabled: false
      lint-enabled: true