---
on:
  pull_request:
    branches:
      - main

name: Commit lint
jobs:
  lint:
    uses: nrkno/github-workflow-semantic-release/.github/workflows/workflow.yaml@b97399abef4d6647db11798db6d81e623b862615 # v4.19.0
    with:
      runs-on: ubuntu-latest
      release-enabled: false
      lint-enabled: true