---
on:
  pull_request:
    branches:
      - main

name: Commit lint
jobs:
  lint:
    uses: nrkno/github-workflow-semantic-release/.github/workflows/workflow.yaml@72621336ddba68f8db2ce914154001ecb6e3c57e # v4.17.0
    with:
      runs-on: ubuntu-latest
      release-enabled: false
      lint-enabled: true